### ISSUE TITLE
[question] solidifying the basics

### ISSUE THREAD

**Issue by justinhelmer** [brycebaril/through2-filter#4]
@brycebaril - thank you for this powerful tool.

I am familiar with the power of streaming and I am trying to become more comfortable with it. I am stuck on a simple pipe:

``` js
var version = /\d+\.\d+\.\d+/;
var scrub = filter({wantStrings: true}, function (str) {
  return version.exec(str)
});

gulp.src(pkg)
          .pipe(bump(options)) // bump version in package.json
          //.pipe(gulp.dest(process.cwd()))
          .pipe(scrub) // scrub version number from output buffer
          .pipe(gulp.dest('out')) // write version number to disk (not the final; just to test)
```

Can you help me fill in the gaps in my lack of understanding?

I appreciate your time with this.

**Comment by justinhelmer** [comment]
Here is the associated output when running this code:

```bash
  dest.on('unpipe', onunpipe);
      ^
TypeError: Cannot read property 'on' of undefined
    at Transform.Readable.pipe (/Users/justin/workspace/npm-publish-release/node_modules/gulp-bump/node_modules/readable-stream/lib/_stream_readable.js:516:7)
    at bumpPackageJson (/Users/justin/workspace/npm-publish-release/bin/npm-publish-release.js:80:12)
    at /Users/justin/workspace/npm-publish-release/bin/npm-publish-release.js:37:3
    at Object.<anonymous> (/Users/justin/workspace/npm-publish-release/bin/npm-publish-release.js:132:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

it breaks at `.pipe(scrub)`

Cheers.

**Comment by brycebaril** [comment]
Hi @justinhelmer!

After looking at [gulp-bump](http://npm.im/gulp-bump) I'm not immediately sure why you'd see that, but it looks like it could be an error inside of `gulp-bump` (hard to tell if the stack trace even gets to your through2-filter function)

I'm also not sure that `through2-filter` is the module you're looking for here, you may want [through2-map](http://npm.im/through2-map) or may need to use [split](http://npm.im/split) to do the line-split first (though then you're at the mercy of file formatting!).

`through2-filter` is like Array#filter where if you return a "truish" value it will keep the chunk/record, otherwise it will skip.

`through2-map` is like Array#map where if you return something it replaces the record with what you return.

It looks like what you're doing is:
1. grabbing all package.json files
2. doing a npm version bump on each of them
3. extracting the new version numbers
4. writing those to disk

Not knowing a lot about `gulp.src` I'm assuming it streams the whole package.json files as one piece each. A lot of node streams are just pieces of the content, but it seems like the case where you're sending multiple files that it would buffer those to send whole files down the pipeline.

I like to think of streams like a an assembly line where each chunk or record is a component being passed down each piece of the pipeline. Those pieces of the pipeline can then operate on those components before passing them along.

In the case of `through2-filter` the function is to look at the component and either pass it along or throw it out. In the case of `through2-map` the function is to look at the component and pass along something else instead (usually an altered version).

What I might try would be something like this, assuming I have your workflow correct:

```js
const map = require('through2-map')

const scrub = map({wantStrings: true}, function mapper(packageJson) {
  var packageObj
  try {
    packageObj = JSON.parse(packageJson)
  } catch (e) {
    // bad json?
    return this.emit('error', e)
  }
  return packageObj.version
})

gulp.src(pkg)
  .pipe(bump(options))
  .pipe(scrub)
  .pipe(process.stdout)
```

Helpful tips:
* you can pipe to `process.stdout` as long as it isn't an `objectMode` stream for easier debugging
* [terminus](http://npm.im/terminus) is also a good tool for the tail end of a stream if you need more complicated debugging than `process.stdout`

**Comment by justinhelmer** [comment]
@brycebaril - You are the man. I'm incredibly grateful for the thoughtful response. I learned so much in the last 5 minutes.

Because you have shown willingness, I hope you do not mind If I ask you a couple more questions. I think I may have miscommunicated some things initially.

I apologize for assuming you were familiar with `gulp`; it is actually their project that led me here! It's an automation tool that is building a significant amount of traction right now for its use of streaming.

Turns out much of their foundation is built on your work ;-) Another great example of community software bringing the whole industry forward.

If you are interested:
[gulpjs/gulpjs](https://github.com/gulpjs/gulp) --> [gulpjs/vinyl-fs](https://github.com/gulpjs/vinyl-fs) --> `brycebaril/through2-filter`

----

For my particular use-case, I am just assuming a single `package.json` file from the current working directory. I was looking around for the easiest way to scrub a string from the stream based on some sort of regex. Then I found all of your goodies.

In my "example", I am only piping to `gulp.dest` to test things; again, attributed to my being so new in this area and not knowing a better way. Now I know one thanks to you ;-)

The final goal is closer to:

1. bump a single `package.json` (`gulp-bump')
2. with the same stream, extract the _new_ `X.X.X` string
3. write the _new_ `package.json` back to its original location
4. end the stream with the version number for further use in the program

----

Based on your _assembly line_ analogy, it seems like I am trying to do something that isn't possible, because `filter` or `map` do what `filter` or `map` should, which means the buffer at **(3)** would only contain the bytes that represent the `X.X.X`.

Am I looking at this all wrong? Or is there some way to intercept these chunks while still passing everything through?

I really appreciate wherever you can help.

**Comment by justinhelmer** [comment]
Also may be worth noting that this does what I would like it to, but without the benefits that your toolset brings:

```js
gulp.src(pkg)
    .pipe(bump(bumpOptions))
    .pipe(gulp.dest(process.cwd()))
    .on('end', function(err) {
      var version = require(pkg).version; // read from disk :-(
    });
```

Thanks again for everything.

**Comment by brycebaril** [comment]
Sure thing!

This should still work with streams, they can be composed to do pretty much anything (imagine an assembly line with branches)

The way that the gulp tooling works might constrain you such that you can't "end" with the version number from the stream, as the `gulp.dest` is likely a `Writable` and not a `Transform` (so it doesn't implement a `Readable` interface) and therefore it wants to be on the end of the pipeline.

You could branch the stream here if you wanted, but to get a single value out it may be overkill.

Here's the branching example:

```js
// you can save the streams before composing them
var read = gulp.src(pkg)
var bumpStream = bump(bumpOptions)
var write = gulp.dest(process.cwd())
var getVersion = scrub // from above more-or-less

// create a stream endpoint which is the package.json + bump
var bumped = read.pipe(bumpStream)

// write it to the file
bumped.pipe(write)

// also (separately) send it to getVersion
var versionStream = bumped.pipe(getVersion)

// this is a bit ugly but much smaller than getting into making a pure Writable stream for the one chunk:
versionStream.on('data', function (version) {
  // version should be the version you want
})
```

That's likely overkill for what you're trying to do, however. I've got another module called [throug2-spy](http://npm.im/throught2-spy) that has a very similar use-case in the README.

```js
const spy = require('through2-spy')

const versionRe = /(\d+\.\d+\.\d+)/
const versionSpy = spy({wantStrings: true}, function (contents) {
  if (versionRe.test(contents)) {
    this.emit('version', versionRe.exec(contents)[0])
  }
})

var pipeline = gulp.src(pkg)
  .pipe(bump(bumpOptions))
  .pipe(versionSpy) // save the pipeline in order to connect to the correct EventEmitter (most events will not propagate through `.pipe` pipelines)

// finish the pipeline
pipeline.pipe(gulp.dest(process.cwd()))

// set up the version listener
pipeline.on('version', console.log)
```

As for the error you're getting, let me see if I can reproduce it locally to dig into it.

**Comment by justinhelmer** [comment]
You have a way of illustrating things that is very helpful.

I have a long laundry list today, but should have some free time this evening to give [through2-spy](https://www.npmjs.com/package/through2-spy) a go. Chances are you will beat me to it ;-)

I cannot thank you enough.

Cheers

**Comment by justinhelmer** [comment]
In case you are interested in taking a closer look at where I stand now: [the specific implementation in question](https://github.com/justinhelmer/npm-publish-release/blob/master/index.js#L71)
